---
title: R语言统计入门-第十一章
author: Dr.二哈
date: '2018-09-10'
slug: r语言统计入门-第十一章
categories:
  - R
  - 统计
tags:
  - R
  - 统计
header:
  caption: ''
  image: ''
---

# 第十一章 多元回归

终于到了在统计中最常见的多元回归了~这本书之前都在讲什么

首先介绍下多元回归的基本模型：
$$
y=\beta_0+\beta_1x_1+\cdot\cdot\cdot+\beta_kx_k+\epsilon
$$
其中，$x_1,...,x_k$等是解释变量（也叫作预测变量）；模型参数$\beta_1,...,\beta_k$可通过最小二乘法估计得出（具体参见6.1节）。

## 11.1 多维数据绘图

下面以Altman（1991）提到的一个关于囊胞性纤维症患者肺功能的研究为例子。数据包含在ISwR包内的cystfibr数据框中。

使用pairs函数可以绘制数据集中任意两个变量间的散点图：

```{R}
library(ISwR)
par(mex = 0.5)
pairs(cystfibr, gap = 0, cex.labels = 0.9)
```

 在这个代码中，参数gap和cex.lables用来控制图形的外观。前者用来移除各个子图之间的图间距，后者用来缩放图中的字号，而绘图命令mex则用来减少图形边界的行间距。

用plot命令也能做出类似的图：

```{R}
plot(cystfibr)
```

用pairs命令得到的那个图，各个子图相对较小，不适合直接放在论文中。不过，这种图形可以清晰的看到多维数据的整体情况，比如，就可以看到age、height和weight具有强相关关系。

为了便于直接引用cystfibr数据集中的变量。可以将该数据集加入到当前的搜索路径中：

```{R}
attach(cystfibr)
```

## 11.2 模型设定和模型输出

多元回归分析的模型是通过在模型公式中的解释变量（~应该就是自变量）之间添加+号来实现：

```{R}
#注意一点，在之前分工作目录中可能会存在名称相同的变量，比如age这个变量，因此在运行这个命令前，需要清空工作目录。
lm(pemax~age+sex+height+weight+bmp+fev1+rv+frc+tlc)
```

这个公式意思就是，pemax这个变量可由一个包含变量age、sex等组成的模型来描述（pemax是患者的最大呼气压力）。

与前面一样，lm函数返回的结果有限，然而，借助summary函数可以得到更多有趣的结果：

```{R}
summary(lm(pemax~age+sex+height+weight+bmp+fev1+rv+frc+tlc))
```

注意，这个结果表明所有变量对应的 *t* 值都不显著，但是，联合 *F* 检验的结果却是显著的，这一定是有原因的。

这个原因就在于，*t* 检验说明的是仅仅是，当从模型中删除某个变量而保留其他变量时模型的变化结果；对于变量在简化模型中是否统计显著，则没有做出说明；值得注意的是，*t* 检验认为**没有一个变量**是**不能**从模型中删除的。

注意，输出结果中未调整R^2^（Multiple R-squared）和调整后R^2^（Adjusted R-squared）有较大差异，这归咎于模型中较多的变量个数，而这个与方差的自由度密切相关。前者表示的是与空模型相对的残差平方和的变化，后者对应的是残差方差的类似变化：

```{R}
1-25.5^2/var(pemax)
```

其中，25.5这个数字取自summary函数输出结果中的**残差标准误（Residual standard error）**。通过anova函数可以得到多元回归分析对应的方差分析表，该表给出了一个截然不同的模型结果：

```{R}
anova(lm(pemax~age+sex+height+weight+bmp+fev1+rv+frc+tlc))
```

注意，除了最后一行（对应于变量tlc）之外，这里的 *F* 检验结果与summary函数输出的 *t* 检验结果几乎完全相悖。这里，age变量的检验结果变得显著了，导致这种结果的原因在于这里的检验过程是逐步进行的；具体而言，对应于（从下至上）将变量逐个从模型中移除，直至剩下age变量。在该过程中，变量bmp的检验结果一度接近5%的临界点，但考虑到检验的个数，这一结果几乎不显著。

在8次独立的检验中，结果给出小于等于0.053的 *p* 值的概率仅仅略高于35%。虽然ANOVA表中的检验并非完全独立，但是其近似结果还是不错的。

ANOVA表的输出结果表明在模型已包含age变量的情况下，再添加其他变量，模型准确度并未得到显著的提高。可以进行联合检验，看看是否可以将age以外的变量全部去掉，做法是求贡献值的平方和加，再对总和进行 *F* 检验：

```{R}
955.4+155.0+632.3+2862.2+1549.1+561.9+194.6+92.4
```

```{R}
7002.9/8
```

```{R}
875.36/648.7
```

```{R}
1-pf(1.349407, 8,15)
```

对应于去掉边框线的表格，它看起来是这样的：

|          |  Df  | Sum Sq  | Mean Sq |   F    | Pr(>F)  |
| -------- | :--: | :-----: | :-----: | :----: | :-----: |
| age      |  1   | 10098.5 | 10098.5 | 15.566 | 0.00130 |
| others   |  8   | 7002.9  |  875.4  | 1.349  | 0.29351 |
| Residual |  15  | 9731.2  |  648.7  |        |         |

这个表格是自己根据数据整理的~不是系统的输出。

如要直接得到上述结果，可运行：

```{R}
m1 <- lm(pemax~age+sex+height+weight+bmp+fev1+rv+frc+tlc)
m2 <- lm(pemax~age)
anova(m1, m2)
```

## 11.3 模型筛选

R有一个按照赤池信息准则（Akaike Information Criterion）进行模型筛选的函数step()。而这个本书不讲~~

本书只使用一种较为简单的人工向后消元法。

下面是一个模型降阶的例子，注意，为减少输出结果占用的空间，对输出信息进行了编辑：

```{R}
#书上是只保留了Coefficients这一项
summary(lm(pemax~age+sex+height+weight+bmp+fev1+rv+frc+tlc))
```

人工进行模型降阶的优点在于该模型引入逻辑结构。在本利中，很自然地会先想到去掉肺功能的指标。

```{R}
summary(lm(pemax~age+sex+height+weight+bmp+fev1+rv+frc))
```

```{R}
summary(lm(pemax~age+sex+height+weight+bmp+fev1+rv))
```

```{R}
summary(lm(pemax~age+sex+height+weight+bmp+fev1))
```

```{R}
summary(lm(pemax~age+sex+height+weight+bmp))
```

上上述结果看，去掉4个肺功能相关的变量没什么不妥，接下来尝试删除那些描述病人身体发育状态或尺寸信息的变量。在开始时，尽量避免删除weight和bmp变量，因为它们对应的 *p* 值很接近5%的显著性界限。

```{R}
summary(lm(pemax~age+height+weight+bmp))
```

```{R}
summary(lm(pemax~height+weight+bmp))
```

```{R}
summary(lm(pemax~weight+bmp))
```

```{R}
summary(lm(pemax~weight))
```

注意，一旦删除age和height变量，变量bmp就不再显著了。在原文献（Altman，1991）中，变量weight、feval和bmp在最终结果中对应的 *p*值都低于5%。然而，并非所有模型降阶过程都是如此。

特别关注变量age、weight和height是个不错的想法，因为在处理儿童和青少年对应的数据时，这些变量表现出很强的相关性。

```{R}
summary(lm(pemax~age+height+weight))
```

```{R}
summary(lm(pemax~age+height))
```

```{R}
summary(lm(pemax~age))
```

```{R}
summary(lm(pemax~height))
```

从上面的结果可以看出，对于变量weight、height和age，没有证据表明哪个比另外两个好。上面所用的消元方法之所以在最后仅留下了weight作为自变量，完全是出于偶然。

## 练习题

1. 在数据集secher中，对出生体重、腰围和二项骨的直径变量进行对数变换后可得到很好的数据分析结果。请拟合出生体重的预测表达式。在模型中同时纳入腹部直径和二项骨直径时，模型结果如何，模型中两个回归系数之和约为3，如何对其进行解释。
2. 数据集tlc有一个同名变量tlc，这不是一个很好的命名方式，请解释原因。用数据集中的其余变量来解释tlc变量，并对模型的有效性进行解释。
3. 数据集cystfibr的分析过程设计sex变量，它是一个二元变量，如何解释回归结果中对应的系数。
4. 考虑juul2数据集，并筛选出该数据集中年龄超过25岁的子集，用age变量对$\sqrt{igfl}$变量进行回归分析。在扩展模型中加入变量height和变量weight，计算扩展模型对应的方差分析表，有没有意想不到的结果出现，为什么会这样呢。
5. 使用多远回归模型，分析冰结师kfmdata数据集中各个解释变量对牛奶摄入量的影响。注意，这里的sex变量是因子型变量，这对分析过程有什么影响？