---
title: R语言初学者指南-第四章
author: Dr.二哈
date: '2020-03-12'
slug: a-beginner-guide-to-r-chapter4
categories:
  - R
  - 统计
tags:
  - R
  - 统计
subtitle: ''
summary: ''
authors: []
lastmod: '2020-03-12T21:20:06+08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
# 第四章 简单的函数
今天开始第四章。如题所见，就是**简单**的函数。
R与其说是一门编程语言，在我看来，它不是，编程只是为了让它更方便快捷，它的初衷，就是统计分析作图。而函数这个概念，在各个编程语言中都出现过，而且地位都不低。这是因为，函数就可以让我们的操作简单起来，算平均值就来个mean()，不用把所有数字加起来再除以个数。
下面看书上的第一节。

## 4.1 tapply函数
书上的逻辑是这样的：

1. 先介绍了一下所用的数据集Vrg，是一个对两个温带（美国黄石国家公园和国家野牛保护区）的草原数据的监控分析。这个研究的目的是确定某段时间丛生禾草群落的生物多样性是否发生变化，如果变了，是否与环境因素有关。生物多样性用物种丰富度来定义也就是下面数据展示中的变量**R**，即每个地点的不同种群数量。研究识别出大约90个物种，数据来自于8个时间截面（也就是变量**Transect**，对，没看错，中文版就是时间截面），每个截面大约是4-10年，总共选取58个观测值：
```{R}
Veg <- read.table(file = "F:\\database\\RBook\\Vegetation2.txt",
                  header = TRUE)
head(Veg, n=20L)
names(Veg)
str(Veg)
```

2. 然后算了下8个时间截面的总体物种平均丰富度m以及每个时间截面的平均丰富度m1-m8，并做出了一个向量：
```{R}
m <- mean(Veg$R)
m1 <- mean(Veg$R[Veg$Transect==1])
m2 <- mean(Veg$R[Veg$Transect==2])
m3 <- mean(Veg$R[Veg$Transect==3])
m4 <- mean(Veg$R[Veg$Transect==4])
m5 <- mean(Veg$R[Veg$Transect==5])
m6 <- mean(Veg$R[Veg$Transect==6])
m7 <- mean(Veg$R[Veg$Transect==7])
m8 <- mean(Veg$R[Veg$Transect==8])
c(m,m1,m2,m3,m4,m5,m6,m7,m8)
```

3. 大家也看出来了，算每个时间截面的平均丰富度，要是这么做就太麻烦了，能不能简单点呢。答案是有的，就是tapply函数。先演示一下：
```{R}
tapply(Veg$R, Veg$Transect, mean)
#或者
tapply(X = Veg$R, INDEX = Veg$Transect, FUN = mean)
```
解释一下，看第二个语句就应该明白了。tapply这个函数常用的有3个参数，**x=……**是告诉它，我要对哪个数据集中的哪个变量操作，**INDEX=……**是告诉它，我要以什么水平来处理这个**x**，最后的**FUN=……**就是告诉它，我要对**x**做什么运算，可以用内置的函数比如mean，sd什么的，也可以用自己编写的函数。
**注意大小写。**
同理，标准差sd，方差，长度什么的都可以。
```{R}
Me <- tapply(Veg$R, Veg$Transect, mean)
Sd <- tapply(Veg$R, Veg$Transect, sd)
Le <- tapply(Veg$R, Veg$Transect, length)
#然后用cbind组合起来
cbind(Me,Sd,Le)
```
第一节就没了，书上还分了两个小节…………咋想的。

## 4.2 sapply函数和lapply函数
大家可能也发现了，我并没用tapply函数计算整个变量**R**的平均值。是因为这个整体的平均值比较简单。但是如果要一次性输出Veg数据集中所有数值型变量的平均值呢，该怎么做？
这个工作要交给sapply函数,比如我就想一次性输出变量**R**：**ROCK**，**LITTER**，**ML**，**BARESOIL**的平均值：
```{R}
sapply(Veg[, 5:9], FUN = mean)
```
这个方括号中的**5:9**指的就是这5个变量。
那这小节标题中的lapply呢，它是干什么的。
还是用例子来说明，我还是计算着5个变量的平均值：
```{R}
lapply(Veg[, 5:9], FUN = mean)
```
发现差异了吗？sapply输出结果是个向量，而lapply输出的结果却是个列表（list）。
这里要注意一点，lappy和sapply中包含数据的变量（对，没看错，中文版就是这么写的，其实指的就是那个**x**）必须是个**数据框**，要是这么写，就错了：
```{R}
sapply(cbind(Veg$R, Veg$ROCK, Veg$LITTER, Veg$ML, Veg$BARESOIL), FUN = mean)
```
它会输出一个很长的向量，根本不是你想要的。原因就在于cbind输出的不是数据框。
可以改成这样：
```{R}
sapply(data.frame(cbind(Veg$R, Veg$ROCK, Veg$LITTER, Veg$ML, Veg$BARESOIL)), FUN = mean)
```
但是对比之前的结果，又有不同的地方，这个语句输出的结果中，丢失了变量标签，只有X1什么的。有两种解决方法，一是在运行sapply之前就生成一个合适的数据框，二是在用cbind结合数据后再用colnames函数来加上标签。

## 4.3 summary函数
这个函数，看名字就知道了，会输出变量信息。相当于统计概要：
```{R}
Z <- cbind(Veg$R, Veg$ROCK, Veg$LITTER)
colnames(Z) <- c("R", "ROCK", "LITTER")
summary(Z)
```
你看结果，最小值，第一四分位数，中位数，平均值，第三四分位数，最大值都出来了。
下面的语句也可以输出这样的结果：
```{R}
summary(Veg[, c("R", "ROCK", "LITTER")])
summary(Veg[, c(5, 6, 7)])
```
道理是一样的。

## 4.4 table函数
这里以第二章的习题1和7为例，引入鹿的数据，这些数据来源于不同的农场、月份、年份和性别。这项研究的一个目的就是找出寄生虫*E.cervi*的数量和动物长度的关系（对，你没看出，中文版就是动物长度），而这种关系可能与农场、月份、年份和性别都有关系（对，就是关系与什么什么有关系，中文版就是这么写的），为了验证这一点，统计模型中就要有相互作用。但是，如果某些年份没有进行雌性的抽样，或者某些年份一些农场没有提供抽样，就会出现问题，因为这就形成了缺失值。
tabble函数的作用就是用来了解每个农场提供抽样动物的数量，每个性别和年份观察值的数量。
```{R}
Deer <- read.table(file = "F:\\database\\RBook\\Deer.txt", header = TRUE, fill=TRUE)
head(Deer, n = 20L)
names(Deer)
str(Deer)
```
原文中这个命令并没有**fill=TRUE**这个参数，我为什么要加上呢，因为没有的话会报错：“Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : line 657 did not have 9 elements”，其实文件中第657行是有9个元素的，所以我加上这个参数让它忽略掉。
变量中，农场分别采用AL、AU等表示，就是字符串，而其他变量都是数值或者整数型向量。那每个农场的观测值数量就可以这么来获得：
```{R}
table(Deer$Farm)
```
可以看到，有的农场（MO）抽取了278个样本，而有的农场（SAL）仅抽取了1个样本。
然后再看看性别和年份：
```{R}
table(Deer$Sex, Deer$Year)
```
这个结果中横向的0，1，2，3，4，5，99代表2000，2001，2002，2003，2004，2005和1999年，纵向的1和2代表性别。
可以发现在1999年，只有一种性别的鹿被检测了。如果不知道这个，在后续处理中包含性别/年份交互作用项的数据就会报错。

## 4.5 我们学习了哪些函数
自己去整理去。

## 4.6 习题
1. 使用tapply，sapply和lappy函数来计算每个月的平均值：
文件*temperature.xls*包含了荷兰海岸线上31个不同地点的温度观测值。抽样开始于1990年，结束于2005年12月，为期16年，根据季节的不同，抽样频率为每月0-4次。
以月为单位计算所有观测点的温度平均值，最终结果应该是一个16×12的变量。再计算每个月的观测值得标准差和数量。
2. 使用table函数来处理温度数据：
使用习题1中的数据，确定每个观测点的观测值数量。每年记录了多少个观测值？每个观测点每年记录了多少观测值？

```{R}

```